"""Gene and Enzyme cards (equivalent to Noita Spells) for Organ-Cannulas."""

from dataclasses import dataclass, field
from enum import Enum
from typing import List, Optional, Tuple

from py_noita.simulation.materials import (
    MAT_ACID,
    MAT_AIR,
    MAT_ASH,
    MAT_BILE,
    MAT_BIOGAS,
    MAT_BLOOD,
    MAT_BONE,
    MAT_BONE_CHIP,
    MAT_CHITIN,
    MAT_FIRE,
    MAT_LYMPH,
    MAT_MUTAGEN,
    MAT_NERVE,
    MAT_PUS,
    MAT_SPORES,
)


class GeneType(Enum):
    PROJECTILE = "PROJECTILE"
    TRIGGER = "TRIGGER"
    MODIFIER = "MODIFIER"
    MULTICAST = "MULTICAST"
    META = "META"
    PASSIVE = "PASSIVE"


@dataclass
class Gene:
    """A genetic sequence card installed in an Organ-Cannula."""
    id: str
    name: str
    gene_type: GeneType
    description: str

    # Energy & timing
    biomass_cost: float = 10.0
    cast_delay_mod: float = 0.0      # Added to cannula cast delay (seconds)
    recharge_mod: float = 0.0        # Added to cannula recharge time (seconds)

    # Projectile properties (for PROJECTILE and TRIGGER types)
    damage: float = 12.0
    speed: float = 6.0
    lifetime: int = 70               # Ticks
    radius: float = 2.5
    spread_mod: float = 0.0
    bounce: int = 0
    piercing: bool = False
    homing: bool = False
    trail_material: int = MAT_AIR
    impact_material: int = MAT_AIR
    impact_material_count: int = 0
    explosion_radius: int = 0

    # Triggers & Formations
    trigger_type: str = "NONE"       # "NONE", "IMPACT", "TIMER", "PROXIMITY", "PENETRATION"
    proximity_radius: float = 0.0
    formation_type: str = "NONE"     # "NONE", "DOUBLE_HELIX", "FAN_3", "FAN_5", "RADIAL_8", "RADIAL_12", "ORBITAL_2", "ORBITAL_4", "FRONT_BACK", "TRI_DIRECTIONAL", "QUAD_CARDINAL", "HEX_BURST", "LINE_STREAM"
    pattern: str = "NORMAL"          # "NORMAL", "HELIX_A", "HELIX_B", "BOOMERANG", "ORBIT"
    vampiric: bool = False
    gravity: float = 0.0
    critical_chance: float = 0.0
    slow_effect: bool = False

    # Meta-Gene properties (Divide By, Loops, Copy)
    meta_type: str = "NONE"          # "NONE", "DIVIDE_2", "DIVIDE_3", "DIVIDE_4", "DIVIDE_10", "LOOP_FIRST", "RANDOM_DISCARD", "COPY_FIRST", "COPY_LAST"
    meta_multiplier: int = 1


    # Multicast count (for MULTICAST types)
    multicast_count: int = 1

    # Icon RGB color for UI rendering
    color: Tuple[int, int, int] = (200, 200, 200)


GENE_LIBRARY: List[Gene] = [
    # =========================================================================
    # 1. BASE & NEW PROJECTILES (47 Cards)
    # =========================================================================
    Gene(
        id="BONE_SPIKE",
        name="Knochenspeer",
        gene_type=GeneType.PROJECTILE,
        description="Ein spitzer Knochensplitter mit hoher Geschwindigkeit und moderatem Schaden.",
        biomass_cost=8.0,
        cast_delay_mod=0.04,
        damage=15.0,
        speed=8.5,
        lifetime=65,
        radius=2.0,
        impact_material=MAT_BONE_CHIP,
        impact_material_count=4,
        color=(235, 230, 215),
    ),
    Gene(
        id="ACID_GLOBULE",
        name="Säuregalle",
        gene_type=GeneType.PROJECTILE,
        description="Schwerer Magensäure-Ballen, der bei Aufprall in ätzende Säure zerspritzt.",
        biomass_cost=20.0,
        cast_delay_mod=0.18,
        damage=22.0,
        speed=4.5,
        lifetime=55,
        radius=3.5,
        impact_material=MAT_ACID,
        impact_material_count=16,
        color=(70, 255, 30),
    ),
    Gene(
        id="BILE_NEEDLE",
        name="Gallen-Nadel",
        gene_type=GeneType.PROJECTILE,
        description="Feine, giftige Galle-Projektile mit minimalem Rückstoß und schneller Kadenz.",
        biomass_cost=5.0,
        cast_delay_mod=-0.04,
        damage=7.0,
        speed=10.0,
        lifetime=45,
        radius=1.5,
        impact_material=MAT_BILE,
        impact_material_count=3,
        color=(170, 200, 25),
    ),
    Gene(
        id="PARASITE_LEECH",
        name="Parasiten-Egel",
        gene_type=GeneType.PROJECTILE,
        description="Kriecht durch Gewebe, saugt Blutzellen an und hinterlässt Blutspuren.",
        biomass_cost=15.0,
        cast_delay_mod=0.12,
        damage=18.0,
        speed=5.0,
        lifetime=90,
        radius=3.0,
        trail_material=MAT_BLOOD,
        impact_material=MAT_BLOOD,
        impact_material_count=8,
        color=(185, 25, 45),
    ),
    Gene(
        id="NERVE_BOLT",
        name="Nerven-Blitz",
        gene_type=GeneType.PROJECTILE,
        description="Elektrisierender Nervenimpuls, der organisches Gewebe durchzuckt.",
        biomass_cost=18.0,
        cast_delay_mod=0.08,
        damage=25.0,
        speed=12.0,
        lifetime=35,
        radius=2.0,
        piercing=True,
        color=(40, 220, 255),
    ),
    Gene(
        id="BONE_BOMB",
        name="Knochen-Tumor (Bombe)",
        gene_type=GeneType.PROJECTILE,
        description="Explosive Knochenkapsel mit verheerender Druckwelle und Kraterbildung.",
        biomass_cost=45.0,
        cast_delay_mod=0.45,
        damage=75.0,
        speed=4.0,
        lifetime=80,
        radius=5.0,
        explosion_radius=18,
        color=(245, 120, 60),
    ),
    Gene(
        id="CARTILAGE_BUCKSHOT",
        name="Knorpel-Schrot",
        gene_type=GeneType.PROJECTILE,
        description="Zersplittert in eine Fächergarbe scharfkantiger Knorpelschuppen.",
        biomass_cost=14.0,
        cast_delay_mod=0.15,
        damage=28.0,
        speed=7.0,
        lifetime=40,
        radius=3.2,
        spread_mod=12.0,
        impact_material=MAT_BONE_CHIP,
        impact_material_count=8,
        color=(220, 205, 180),
    ),
    Gene(
        id="PLASMA_TENDRIL",
        name="Plasma-Tendril",
        gene_type=GeneType.PROJECTILE,
        description="Schlängelnder Bio-Plasmafaden, der Gewebe mit Sinuswellen durchbohrt.",
        biomass_cost=22.0,
        cast_delay_mod=0.10,
        damage=32.0,
        speed=8.0,
        lifetime=60,
        radius=2.8,
        pattern="HELIX_A",
        color=(255, 80, 220),
    ),
    Gene(
        id="CYTOKINE_LASER",
        name="Zytokin-Laser",
        gene_type=GeneType.PROJECTILE,
        description="Hyperschneller Zytotoxischer Punktstrahl mit extremer Durchschlagskraft.",
        biomass_cost=24.0,
        cast_delay_mod=-0.02,
        damage=30.0,
        speed=18.0,
        lifetime=30,
        radius=1.8,
        piercing=True,
        color=(240, 250, 80),
    ),
    Gene(
        id="SPORE_MINE",
        name="Sporen-Mine",
        gene_type=GeneType.PROJECTILE,
        description="Schwebende biologische Mine, die bei Kontakt oder Verfall zerspringt.",
        biomass_cost=16.0,
        cast_delay_mod=0.20,
        damage=40.0,
        speed=1.2,
        lifetime=120,
        radius=4.5,
        explosion_radius=14,
        trail_material=MAT_SPORES,
        color=(140, 210, 40),
    ),
    Gene(
        id="BONE_BOOMERANG",
        name="Knochen-Bumerang",
        gene_type=GeneType.PROJECTILE,
        description="Gekrümmte Knochensichel, die im Flug umkehrt und zum Symbioten zurückkehrt.",
        biomass_cost=16.0,
        cast_delay_mod=0.08,
        damage=22.0,
        speed=9.0,
        lifetime=70,
        radius=2.5,
        pattern="BOOMERANG",
        color=(230, 215, 175),
    ),
    Gene(
        id="SLIME_ORB",
        name="Schleim-Kugel",
        gene_type=GeneType.PROJECTILE,
        description="Schwere viskose Schleimmasse, die Ziele kinetisch zurückwirft.",
        biomass_cost=12.0,
        cast_delay_mod=0.14,
        damage=16.0,
        speed=5.5,
        lifetime=65,
        radius=4.0,
        slow_effect=True,
        color=(60, 190, 120),
    ),
    Gene(
        id="FIBRILLIN_DART",
        name="Fibrillin-Pfeil",
        gene_type=GeneType.PROJECTILE,
        description="Nadelspitzer Präzisionspfeil mit laserartiger Flugbahn.",
        biomass_cost=8.0,
        cast_delay_mod=-0.02,
        damage=14.0,
        speed=14.0,
        lifetime=50,
        radius=1.5,
        color=(210, 230, 255),
    ),
    Gene(
        id="CHITIN_SHARD",
        name="Chitin-Splitter",
        gene_type=GeneType.PROJECTILE,
        description="Gehärtete Chitinscherbe, die von harten Wänden abprallt.",
        biomass_cost=10.0,
        cast_delay_mod=0.02,
        damage=15.0,
        speed=8.0,
        lifetime=60,
        radius=2.0,
        bounce=3,
        color=(140, 95, 60),
    ),
    Gene(
        id="ACID_SPIT",
        name="Magensäure-Spritzer",
        gene_type=GeneType.PROJECTILE,
        description="Schnellfeuer-Säureausstoß zum kontinuierlichen Zerfressen von Gewebe.",
        biomass_cost=6.0,
        cast_delay_mod=-0.06,
        damage=8.0,
        speed=9.0,
        lifetime=40,
        radius=2.0,
        impact_material=MAT_ACID,
        impact_material_count=5,
        color=(90, 240, 50),
    ),
    Gene(
        id="LYMPH_DROP",
        name="Lymph-Tröpfchen",
        gene_type=GeneType.PROJECTILE,
        description="Sanftes Tröpfchen aus Abwehrlymphe mit reduzierten Biomassekosten.",
        biomass_cost=4.0,
        cast_delay_mod=-0.05,
        damage=6.0,
        speed=7.5,
        lifetime=45,
        radius=1.8,
        impact_material=MAT_LYMPH,
        impact_material_count=4,
        color=(200, 250, 180),
    ),
    Gene(
        id="HEMO_GLOBIN",
        name="Hämoglobin-Geschoss",
        gene_type=GeneType.PROJECTILE,
        description="Dichtes eisengefülltes Blutgeschoss mit hoher Trägheit.",
        biomass_cost=14.0,
        cast_delay_mod=0.08,
        damage=20.0,
        speed=6.5,
        lifetime=60,
        radius=3.0,
        impact_material=MAT_BLOOD,
        impact_material_count=10,
        color=(160, 15, 30),
    ),
    Gene(
        id="NEURO_SHOCK",
        name="Neuro-Schockwelle",
        gene_type=GeneType.PROJECTILE,
        description="Verzweigender Hochspannungs-Synapsenblitz mit Stun-Effekt.",
        biomass_cost=20.0,
        cast_delay_mod=0.10,
        damage=26.0,
        speed=11.0,
        lifetime=35,
        radius=2.5,
        color=(80, 230, 255),
    ),
    Gene(
        id="PHAGOCYTE_BLOB",
        name="Phagozyten-Klumpen",
        gene_type=GeneType.PROJECTILE,
        description="Kriechende Riesenzelle, die feindliche Strukturen im Flug verschlingt.",
        biomass_cost=25.0,
        cast_delay_mod=0.22,
        damage=34.0,
        speed=3.5,
        lifetime=90,
        radius=5.0,
        color=(190, 205, 45),
    ),
    Gene(
        id="MYELIN_STREAK",
        name="Myelin-Lanze",
        gene_type=GeneType.PROJECTILE,
        description="Fettummantelte Nervenlanze mit enormer aerodynamischer Stabilität.",
        biomass_cost=15.0,
        cast_delay_mod=0.06,
        damage=24.0,
        speed=13.0,
        lifetime=55,
        radius=2.0,
        piercing=True,
        color=(235, 245, 160),
    ),
    Gene(
        id="KERATIN_SPIKE",
        name="Keratin-Dorn",
        gene_type=GeneType.PROJECTILE,
        description="Gepanzerter Horndorn, der solide Knochenstrukturen aufbricht.",
        biomass_cost=16.0,
        cast_delay_mod=0.12,
        damage=25.0,
        speed=8.0,
        lifetime=60,
        radius=2.6,
        color=(180, 160, 130),
    ),
    Gene(
        id="ENZYME_BURST",
        name="Enzym-Eruption",
        gene_type=GeneType.PROJECTILE,
        description="Spritzende Enzymlauge, die lebende Organe in Säureschlamm zersetzt.",
        biomass_cost=18.0,
        cast_delay_mod=0.14,
        damage=21.0,
        speed=6.0,
        lifetime=50,
        radius=3.0,
        impact_material=MAT_ACID,
        impact_material_count=12,
        color=(120, 255, 80),
    ),
    Gene(
        id="BIOGAS_BUBBLE",
        name="Biogas-Blase",
        gene_type=GeneType.PROJECTILE,
        description="Leichte Gasblase, die aufsteigt und bei Zündung explodiert.",
        biomass_cost=12.0,
        cast_delay_mod=0.05,
        damage=15.0,
        speed=4.0,
        lifetime=80,
        radius=3.8,
        gravity=-0.08,
        impact_material=MAT_BIOGAS,
        impact_material_count=10,
        color=(200, 225, 110),
    ),
    Gene(
        id="SCLERA_DISC",
        name="Skleren-Diskus",
        gene_type=GeneType.PROJECTILE,
        description="Rotierende Hornhaut-Klinge, die weiche Gewebeschichten durchschneidet.",
        biomass_cost=15.0,
        cast_delay_mod=0.07,
        damage=20.0,
        speed=10.0,
        lifetime=50,
        radius=2.4,
        bounce=2,
        color=(215, 235, 245),
    ),
    Gene(
        id="COLLAGEN_WHIP",
        name="Kollagen-Peitsche",
        gene_type=GeneType.PROJECTILE,
        description="Elastischer Faserstrang mit weitem Schwungradius.",
        biomass_cost=14.0,
        cast_delay_mod=0.08,
        damage=19.0,
        speed=7.5,
        lifetime=45,
        radius=3.0,
        color=(240, 190, 190),
    ),
    Gene(
        id="OSTEOCLAST_DRILL",
        name="Osteoklasten-Bohrer",
        gene_type=GeneType.PROJECTILE,
        description="Verzehrt Kalk und Knochen im Flug und bohrt tiefe Kavernentunnel.",
        biomass_cost=26.0,
        cast_delay_mod=0.25,
        damage=32.0,
        speed=5.0,
        lifetime=75,
        radius=3.5,
        piercing=True,
        color=(250, 235, 190),
    ),
    Gene(
        id="THROMBUS_SLUG",
        name="Thrombus-Brocken",
        gene_type=GeneType.PROJECTILE,
        description="Gerinnsel aus Blutplättchen mit wuchtigem Aufprallimpuls.",
        biomass_cost=17.0,
        cast_delay_mod=0.16,
        damage=26.0,
        speed=5.5,
        lifetime=65,
        radius=4.0,
        impact_material=MAT_BLOOD,
        impact_material_count=12,
        color=(120, 10, 20),
    ),
    Gene(
        id="MACROPHAGE_POD",
        name="Makrophagen-Kapsel",
        gene_type=GeneType.PROJECTILE,
        description="Biologische Jägerzelle mit Zielsuch-Pheromonen.",
        biomass_cost=22.0,
        cast_delay_mod=0.18,
        damage=27.0,
        speed=6.0,
        lifetime=85,
        radius=3.2,
        homing=True,
        color=(205, 175, 40),
    ),
    Gene(
        id="ADRENALINE_SPURT",
        name="Adrenalin-Injektor",
        gene_type=GeneType.PROJECTILE,
        description="Pfeilschnelle Zwergdosis, die die Waffenkadenz dramatisch beschleunigt.",
        biomass_cost=5.0,
        cast_delay_mod=-0.08,
        recharge_mod=-0.05,
        damage=6.0,
        speed=15.0,
        lifetime=35,
        radius=1.4,
        color=(255, 140, 60),
    ),
    Gene(
        id="MELANIN_BLAST",
        name="Melanin-Dunkelstrahl",
        gene_type=GeneType.PROJECTILE,
        description="Konzentriertes Pigmentgeschoss, das feindliche Sicht absorbiert.",
        biomass_cost=16.0,
        cast_delay_mod=0.08,
        damage=23.0,
        speed=9.0,
        lifetime=50,
        radius=2.5,
        color=(45, 30, 40),
    ),
    Gene(
        id="GASTRIC_VORTEX",
        name="Magen-Strudel",
        gene_type=GeneType.PROJECTILE,
        description="Wirbelnde Verdauungskugel, die Materie ansaugt und verflüssigt.",
        biomass_cost=30.0,
        cast_delay_mod=0.28,
        damage=42.0,
        speed=4.5,
        lifetime=80,
        radius=4.8,
        impact_material=MAT_ACID,
        impact_material_count=20,
        color=(80, 230, 90),
    ),
    Gene(
        id="SPINAL_BOLT",
        name="Spinal-Blitz",
        gene_type=GeneType.PROJECTILE,
        description="Reiner Rückenmarks-Impuls mit durchdringender Schockwirkung.",
        biomass_cost=21.0,
        cast_delay_mod=0.06,
        damage=29.0,
        speed=13.5,
        lifetime=40,
        radius=2.0,
        piercing=True,
        color=(120, 240, 255),
    ),
    Gene(
        id="NEURON_PULSE",
        name="Neuron-Puls",
        gene_type=GeneType.PROJECTILE,
        description="Pulsierende bio-elektrische Sphäre mit wellenförmiger Ausbreitung.",
        biomass_cost=15.0,
        cast_delay_mod=0.05,
        damage=18.0,
        speed=7.0,
        lifetime=65,
        radius=3.0,
        color=(60, 210, 255),
    ),
    Gene(
        id="PULMONARY_GUST",
        name="Lungen-Stoss",
        gene_type=GeneType.PROJECTILE,
        description="Druckluftstoß aus der infizierten Lunge mit heftigem Rückstoß.",
        biomass_cost=8.0,
        cast_delay_mod=0.02,
        damage=10.0,
        speed=11.0,
        lifetime=35,
        radius=3.5,
        color=(190, 220, 230),
    ),
    Gene(
        id="RIBOSOME_BEAD",
        name="Ribosomen-Perle",
        gene_type=GeneType.PROJECTILE,
        description="Winziges dichtes Enzymkügelchen für Maschinengewehr-Salven.",
        biomass_cost=3.0,
        cast_delay_mod=-0.05,
        damage=5.0,
        speed=12.0,
        lifetime=38,
        radius=1.2,
        color=(230, 190, 240),
    ),
    Gene(
        id="MITOCHONDRIA_SPARK",
        name="Mitochondrien-Funke",
        gene_type=GeneType.PROJECTILE,
        description="Hochenergetischer ATP-Funke, der brennbares Gas entzündet.",
        biomass_cost=10.0,
        cast_delay_mod=0.02,
        damage=16.0,
        speed=8.5,
        lifetime=45,
        radius=2.0,
        trail_material=MAT_FIRE,
        impact_material=MAT_FIRE,
        impact_material_count=3,
        color=(255, 170, 30),
    ),
    Gene(
        id="HEPATIC_DROP",
        name="Leber-Extrakt",
        gene_type=GeneType.PROJECTILE,
        description="Schweres giftiges Filter-Sekret mit toxischer Langzeitwirkung.",
        biomass_cost=14.0,
        cast_delay_mod=0.09,
        damage=19.0,
        speed=6.0,
        lifetime=60,
        radius=2.7,
        impact_material=MAT_BILE,
        impact_material_count=8,
        color=(145, 175, 20),
    ),
    Gene(
        id="SUTURE_THREAD",
        name="Chirurgischer Faden",
        gene_type=GeneType.PROJECTILE,
        description="Durchdringende Sehnenschnur, die mehrere Gegner in Reihe aufspießt.",
        biomass_cost=17.0,
        cast_delay_mod=0.08,
        damage=22.0,
        speed=10.5,
        lifetime=55,
        radius=1.8,
        piercing=True,
        color=(230, 210, 200),
    ),
    Gene(
        id="BONE_MARROW_BLOB",
        name="Knochenmark-Schleuder",
        gene_type=GeneType.PROJECTILE,
        description="Fettiges nahrhaftes Mark, das beim Zerplatzen Gewebe regeneriert.",
        biomass_cost=20.0,
        cast_delay_mod=0.18,
        damage=24.0,
        speed=5.0,
        lifetime=65,
        radius=3.8,
        color=(245, 180, 150),
    ),
    Gene(
        id="VESICLE_POPPER",
        name="Vesikel-Knaller",
        gene_type=GeneType.PROJECTILE,
        description="Platzen in winzige Knallperlen mit hoher Schockwirkung.",
        biomass_cost=11.0,
        cast_delay_mod=0.04,
        damage=14.0,
        speed=9.5,
        lifetime=40,
        radius=2.2,
        explosion_radius=8,
        color=(250, 110, 140),
    ),
    Gene(
        id="CHONDROCYTE_DART",
        name="Chondrozyten-Pfeil",
        gene_type=GeneType.PROJECTILE,
        description="Elastischer Knorpelpfeil mit mehrfacher Querschläger-Fähigkeit.",
        biomass_cost=12.0,
        cast_delay_mod=0.04,
        damage=16.0,
        speed=8.5,
        lifetime=60,
        radius=2.0,
        bounce=4,
        color=(200, 220, 190),
    ),
    Gene(
        id="AXON_JAVELIN",
        name="Axon-Wurfspieß",
        gene_type=GeneType.PROJECTILE,
        description="Überlanger Nervenfortsatz mit maximaler Schussdistanz.",
        biomass_cost=22.0,
        cast_delay_mod=0.14,
        damage=33.0,
        speed=12.0,
        lifetime=90,
        radius=2.2,
        color=(90, 215, 240),
    ),
    Gene(
        id="CALCIFIED_METEOR",
        name="Verkalkter Meteor",
        gene_type=GeneType.PROJECTILE,
        description="Gigantischer Knochenbrocken, der ganze Cavernenwände zerschmettert.",
        biomass_cost=55.0,
        cast_delay_mod=0.60,
        damage=95.0,
        speed=3.2,
        lifetime=90,
        radius=7.0,
        explosion_radius=26,
        impact_material=MAT_BONE_CHIP,
        impact_material_count=20,
        color=(235, 225, 200),
    ),
    Gene(
        id="DENDRITE_BRANCH",
        name="Dendriten-Zweig",
        gene_type=GeneType.PROJECTILE,
        description="Verästelnder synaptischer Impuls, der Flächenschaden anrichtet.",
        biomass_cost=18.0,
        cast_delay_mod=0.09,
        damage=22.0,
        speed=8.0,
        lifetime=50,
        radius=2.5,
        color=(75, 195, 245),
    ),
    Gene(
        id="PLASMA_GLOB",
        name="Bio-Plasma-Kugel",
        gene_type=GeneType.PROJECTILE,
        description="Glühender Ball aus ionisierter Zellflüssigkeit mit Feuerspur.",
        biomass_cost=26.0,
        cast_delay_mod=0.15,
        damage=38.0,
        speed=7.0,
        lifetime=60,
        radius=3.8,
        trail_material=MAT_FIRE,
        color=(255, 60, 160),
    ),
    Gene(
        id="HISTAMINE_FLARE",
        name="Histamin-Fackel",
        gene_type=GeneType.PROJECTILE,
        description="Entzündungsfördernder Schuss mit hoher Brandgefahr im Wirtsgewebe.",
        biomass_cost=14.0,
        cast_delay_mod=0.06,
        damage=17.0,
        speed=7.5,
        lifetime=55,
        radius=2.5,
        impact_material=MAT_FIRE,
        impact_material_count=6,
        color=(255, 100, 40),
    ),
    Gene(
        id="PRIMORDIAL_BEAM",
        name="Ur-Plasma-Strahl",
        gene_type=GeneType.PROJECTILE,
        description="Uralte hochenergetische Entladung, die Gewebe durchdringt und Mutagen-Rückstände hinterlässt.",
        biomass_cost=32.0,
        cast_delay_mod=0.18,
        recharge_mod=0.25,
        damage=45.0,
        speed=10.0,
        lifetime=110,
        radius=4.0,
        piercing=True,
        trail_material=MAT_MUTAGEN,
        impact_material=MAT_MUTAGEN,
        impact_material_count=5,
        color=(230, 60, 255),
    ),
    Gene(
        id="UR_CYTOKINE",
        name="Ur-Zytokin-Nova",
        gene_type=GeneType.PROJECTILE,
        description="Gewaltige bio-zytotoxische Kugel mit zielsuchendem Vektor und verheerender Sprengkraft.",
        biomass_cost=40.0,
        cast_delay_mod=0.35,
        recharge_mod=0.45,
        damage=65.0,
        speed=5.0,
        lifetime=140,
        radius=6.0,
        homing=True,
        explosion_radius=22,
        color=(255, 230, 40),
    ),

    # =========================================================================
    # 2. TRIGGER & TIMER GENES (28 Cards)
    # =========================================================================
    Gene(
        id="TRIGGER_HIT_BONE",
        name="Knochenspeer [Treffer-Trigger]",
        gene_type=GeneType.TRIGGER,
        description="Knochenspeer, der beim Einschlag die nachfolgende Gen-Sequenz zündet.",
        biomass_cost=12.0,
        cast_delay_mod=0.06,
        damage=12.0,
        speed=8.0,
        lifetime=65,
        radius=2.0,
        trigger_type="IMPACT",
        color=(255, 220, 160),
    ),
    Gene(
        id="TRIGGER_HIT_ACID",
        name="Säure-Impakt-Trigger",
        gene_type=GeneType.TRIGGER,
        description="Detoniert die Folgesequenz bei Aufprall und zerstäubt Magensäure.",
        biomass_cost=15.0,
        cast_delay_mod=0.08,
        damage=14.0,
        speed=7.5,
        lifetime=55,
        radius=2.4,
        trigger_type="IMPACT",
        impact_material=MAT_ACID,
        impact_material_count=8,
        color=(110, 255, 60),
    ),
    Gene(
        id="TRIGGER_HIT_BILE",
        name="Gallen-Impakt-Trigger",
        gene_type=GeneType.TRIGGER,
        description="Zündet Folgesequenz bei Treffer mit toxischem Gallenspritzer.",
        biomass_cost=11.0,
        cast_delay_mod=0.04,
        damage=10.0,
        speed=9.0,
        lifetime=50,
        radius=2.0,
        trigger_type="IMPACT",
        impact_material=MAT_BILE,
        impact_material_count=6,
        color=(175, 220, 30),
    ),
    Gene(
        id="TRIGGER_HIT_BLOOD",
        name="Blut-Impakt-Trigger",
        gene_type=GeneType.TRIGGER,
        description="Setzt bei Treffer die Folgesequenz in einer Blutfontäne frei.",
        biomass_cost=14.0,
        cast_delay_mod=0.06,
        damage=15.0,
        speed=8.0,
        lifetime=60,
        radius=2.5,
        trigger_type="IMPACT",
        impact_material=MAT_BLOOD,
        impact_material_count=10,
        color=(190, 20, 35),
    ),
    Gene(
        id="TRIGGER_HIT_NERVE",
        name="Nerven-Impakt-Trigger",
        gene_type=GeneType.TRIGGER,
        description="Entlädt bei Kontakt die Folgesequenz mit bio-elektrischem Schock.",
        biomass_cost=18.0,
        cast_delay_mod=0.08,
        damage=20.0,
        speed=11.0,
        lifetime=45,
        radius=2.0,
        trigger_type="IMPACT",
        color=(70, 235, 255),
    ),
    Gene(
        id="TRIGGER_HIT_CHITIN",
        name="Chitin-Impakt-Trigger",
        gene_type=GeneType.TRIGGER,
        description="Bricht durch Aufprall entzwei und entlässt die geladene Folgesequenz.",
        biomass_cost=13.0,
        cast_delay_mod=0.05,
        damage=13.0,
        speed=8.5,
        lifetime=55,
        radius=2.2,
        trigger_type="IMPACT",
        color=(160, 110, 70),
    ),
    Gene(
        id="TRIGGER_HIT_KERATIN",
        name="Keratin-Impakt-Trigger",
        gene_type=GeneType.TRIGGER,
        description="Wuchtiger Panzerbrecher, der tief im Ziel die Folgesequenz zündet.",
        biomass_cost=20.0,
        cast_delay_mod=0.12,
        damage=24.0,
        speed=7.0,
        lifetime=60,
        radius=2.8,
        trigger_type="IMPACT",
        color=(210, 185, 140),
    ),
    Gene(
        id="TRIGGER_HIT_PLASMA",
        name="Plasma-Impakt-Trigger",
        gene_type=GeneType.TRIGGER,
        description="Supererhitzter Plasmabolzen, der beim Verglühen die Payload entlädt.",
        biomass_cost=25.0,
        cast_delay_mod=0.15,
        damage=30.0,
        speed=9.5,
        lifetime=50,
        radius=3.0,
        trigger_type="IMPACT",
        color=(255, 90, 210),
    ),
    Gene(
        id="TRIGGER_HIT_PHAGO",
        name="Phago-Impakt-Trigger",
        gene_type=GeneType.TRIGGER,
        description="Amöbische Zelle, die sich am Ziel festsaugt und die Payload ausstößt.",
        biomass_cost=19.0,
        cast_delay_mod=0.14,
        damage=18.0,
        speed=5.0,
        lifetime=75,
        radius=3.5,
        trigger_type="IMPACT",
        color=(185, 195, 30),
    ),
    Gene(
        id="TRIGGER_TIMER_SPORE",
        name="Sporen-Kapsel [Timer-Trigger]",
        gene_type=GeneType.TRIGGER,
        description="Fliegt vorwärts und detoniert nach 30 Ticks in die nächste Gen-Sequenz.",
        biomass_cost=14.0,
        cast_delay_mod=0.08,
        damage=8.0,
        speed=6.0,
        lifetime=30,
        radius=2.5,
        trigger_type="TIMER",
        trail_material=MAT_SPORES,
        color=(190, 215, 50),
    ),
    Gene(
        id="TIMER_MICRO_BURST",
        name="Mikro-Verfall-Timer (10 Ticks)",
        gene_type=GeneType.TRIGGER,
        description="Extrem kurzer Zeitzünder für sofortige Airburst-Kaskaden.",
        biomass_cost=8.0,
        cast_delay_mod=0.02,
        damage=5.0,
        speed=8.0,
        lifetime=10,
        radius=1.8,
        trigger_type="TIMER",
        color=(255, 180, 80),
    ),
    Gene(
        id="TIMER_SHORT_CYST",
        name="Kurzzeit-Zyste (15 Ticks)",
        gene_type=GeneType.TRIGGER,
        description="Zündet nach kurzem Flugweg (15 Ticks) die gebundene Gen-Sequenz.",
        biomass_cost=10.0,
        cast_delay_mod=0.04,
        damage=7.0,
        speed=7.0,
        lifetime=15,
        radius=2.0,
        trigger_type="TIMER",
        color=(240, 200, 90),
    ),
    Gene(
        id="TIMER_DELAY_SPORE",
        name="Schwebesporen-Timer (25 Ticks)",
        gene_type=GeneType.TRIGGER,
        description="Gleitet 25 Ticks durch die Luft und öffnet dann die Payload-Kammer.",
        biomass_cost=12.0,
        cast_delay_mod=0.06,
        damage=9.0,
        speed=6.5,
        lifetime=25,
        radius=2.2,
        trigger_type="TIMER",
        trail_material=MAT_SPORES,
        color=(160, 230, 60),
    ),
    Gene(
        id="TIMER_MED_BURST",
        name="Mittlerer Zell-Timer (35 Ticks)",
        gene_type=GeneType.TRIGGER,
        description="Zuverlässiger mittellanger Flugtimer (35 Ticks) vor Entfaltung.",
        biomass_cost=14.0,
        cast_delay_mod=0.08,
        damage=11.0,
        speed=7.5,
        lifetime=35,
        radius=2.5,
        trigger_type="TIMER",
        color=(130, 210, 110),
    ),
    Gene(
        id="TIMER_PULSE_BOMB",
        name="Pulsierender Bio-Timer (45 Ticks)",
        gene_type=GeneType.TRIGGER,
        description="Pulsierende Kapsel, die nach 45 Ticks weit im Raum explodiert.",
        biomass_cost=16.0,
        cast_delay_mod=0.10,
        damage=14.0,
        speed=6.0,
        lifetime=45,
        radius=3.0,
        trigger_type="TIMER",
        color=(100, 180, 220),
    ),
    Gene(
        id="TIMER_LONG_FUSE",
        name="Langzeit-Neuro-Timer (60 Ticks)",
        gene_type=GeneType.TRIGGER,
        description="Reist 60 Ticks tief in feindliche Höhlen, bevor die Payload feuert.",
        biomass_cost=18.0,
        cast_delay_mod=0.12,
        damage=15.0,
        speed=8.0,
        lifetime=60,
        radius=2.4,
        trigger_type="TIMER",
        color=(70, 140, 240),
    ),
    Gene(
        id="TIMER_DRIFT_ORGAN",
        name="Drift-Zellen-Timer (75 Ticks)",
        gene_type=GeneType.TRIGGER,
        description="Schwerelos gleitendes Organ mit spätem Zeitzünder für Hinterhalte.",
        biomass_cost=20.0,
        cast_delay_mod=0.15,
        damage=18.0,
        speed=3.0,
        lifetime=75,
        radius=3.6,
        trigger_type="TIMER",
        color=(170, 110, 230),
    ),
    Gene(
        id="TRIGGER_PROX_SENSE",
        name="Bio-Sensor-Näherungszünder",
        gene_type=GeneType.TRIGGER,
        description="Detoniert automatisch, sobald sich ein Feind auf 24 Pixel nähert.",
        biomass_cost=22.0,
        cast_delay_mod=0.10,
        damage=12.0,
        speed=6.5,
        lifetime=90,
        radius=2.8,
        trigger_type="PROXIMITY",
        proximity_radius=24.0,
        color=(255, 60, 100),
    ),
    Gene(
        id="TRIGGER_PROX_BLOOD",
        name="Blutwitterungs-Zünder",
        gene_type=GeneType.TRIGGER,
        description="Reagiert hochempfindlich (30 Pixel Radius) auf organische Gewebezellen.",
        biomass_cost=24.0,
        cast_delay_mod=0.12,
        damage=14.0,
        speed=6.0,
        lifetime=95,
        radius=3.0,
        trigger_type="PROXIMITY",
        proximity_radius=30.0,
        color=(220, 20, 50),
    ),
    Gene(
        id="TRIGGER_PROX_NERVE",
        name="Synaptischer Näherungszünder",
        gene_type=GeneType.TRIGGER,
        description="Erkennt elektrostatische Nervenfelder (26 Pixel) und entlädt die Payload.",
        biomass_cost=25.0,
        cast_delay_mod=0.11,
        damage=15.0,
        speed=7.5,
        lifetime=85,
        radius=2.5,
        trigger_type="PROXIMITY",
        proximity_radius=26.0,
        color=(40, 230, 255),
    ),
    Gene(
        id="TRIGGER_PROX_ACID",
        name="Säure-Drucksensor-Zünder",
        gene_type=GeneType.TRIGGER,
        description="Reagiert auf organische Dichte (22 Pixel) mit ätzendem Payload-Ausstoß.",
        biomass_cost=21.0,
        cast_delay_mod=0.09,
        damage=13.0,
        speed=7.0,
        lifetime=80,
        radius=2.6,
        trigger_type="PROXIMITY",
        proximity_radius=22.0,
        color=(90, 255, 70),
    ),
    Gene(
        id="TRIGGER_PROX_SPORE",
        name="Sporen-Reiz-Zünder",
        gene_type=GeneType.TRIGGER,
        description="Schwebt im Raum und explodiert bei Annäherung eines Opfers (28 Pixel).",
        biomass_cost=20.0,
        cast_delay_mod=0.08,
        damage=11.0,
        speed=4.5,
        lifetime=100,
        radius=3.2,
        trigger_type="PROXIMITY",
        proximity_radius=28.0,
        color=(185, 240, 40),
    ),
    Gene(
        id="TRIGGER_PENETRATION_BONE",
        name="Knochen-Durchschlags-Trigger",
        gene_type=GeneType.TRIGGER,
        description="Durchschlägt Knochenwände und zündet dabei im Durchflug die Payload.",
        biomass_cost=26.0,
        cast_delay_mod=0.15,
        damage=22.0,
        speed=9.0,
        lifetime=70,
        radius=2.5,
        piercing=True,
        trigger_type="PENETRATION",
        color=(245, 230, 190),
    ),
    Gene(
        id="TRIGGER_PENETRATION_FLESH",
        name="Fleisch-Durchdringungs-Trigger",
        gene_type=GeneType.TRIGGER,
        description="Bohrt sich durch Feinde und gibt im Inneren die nächste Sequenz ab.",
        biomass_cost=24.0,
        cast_delay_mod=0.14,
        damage=20.0,
        speed=8.5,
        lifetime=65,
        radius=2.6,
        piercing=True,
        trigger_type="PENETRATION",
        color=(230, 80, 110),
    ),
    Gene(
        id="TRIGGER_PENETRATION_TENDON",
        name="Sehnen-Schnitt-Trigger",
        gene_type=GeneType.TRIGGER,
        description="Trennt Bindegewebe und Sehnen und triggert dabei die Folgesequenz.",
        biomass_cost=25.0,
        cast_delay_mod=0.13,
        damage=21.0,
        speed=10.0,
        lifetime=60,
        radius=2.2,
        piercing=True,
        trigger_type="PENETRATION",
        color=(225, 200, 170),
    ),
    Gene(
        id="TRIGGER_PENETRATION_PLASMA",
        name="Plasma-Kavitations-Trigger",
        gene_type=GeneType.TRIGGER,
        description="Brennt Hohlräume in Gewebe und speit kontinuierlich Payload-Salven.",
        biomass_cost=32.0,
        cast_delay_mod=0.20,
        damage=28.0,
        speed=11.0,
        lifetime=55,
        radius=3.0,
        piercing=True,
        trigger_type="PENETRATION",
        color=(255, 60, 220),
    ),
    Gene(
        id="TRIGGER_PENETRATION_DOUBLE",
        name="Doppel-Penetrations-Trigger",
        gene_type=GeneType.TRIGGER,
        description="Kann 2 feste Hindernisse oder Feinde durchstoßen und je eine Payload zünden.",
        biomass_cost=30.0,
        cast_delay_mod=0.18,
        damage=25.0,
        speed=9.5,
        lifetime=75,
        radius=2.5,
        piercing=True,
        trigger_type="PENETRATION",
        color=(210, 140, 255),
    ),
    Gene(
        id="MUTAGEN_COLLAPSE",
        name="Mutagen-Zellkollaps",
        gene_type=GeneType.TRIGGER,
        description="Löst bei Aufprall eine schwere nukleotidische Implosion aus, die Terrain zerschmettert.",
        biomass_cost=38.0,
        cast_delay_mod=0.22,
        recharge_mod=0.35,
        damage=55.0,
        speed=7.5,
        lifetime=85,
        radius=4.5,
        trigger_type="IMPACT",
        explosion_radius=28,
        trail_material=MAT_MUTAGEN,
        color=(180, 20, 240),
    ),

    # =========================================================================
    # 3. MODIFIERS (36 Cards)
    # =========================================================================
    Gene(
        id="MOD_HOMING",
        name="Pheromon-Peilung",
        gene_type=GeneType.MODIFIER,
        description="Verleiht Projektilen die Fähigkeit, organisch auf Feinde zuzufliegen.",
        biomass_cost=10.0,
        cast_delay_mod=0.05,
        homing=True,
        color=(220, 40, 220),
    ),
    Gene(
        id="MOD_HOMING_STRONG",
        name="Homöostase-Peilung",
        gene_type=GeneType.MODIFIER,
        description="Aggressive bio-magnetische Lenkung mit engsten Kurvenradien.",
        biomass_cost=20.0,
        cast_delay_mod=0.12,
        homing=True,
        color=(255, 30, 180),
    ),
    Gene(
        id="MOD_NECROSIS_DOT",
        name="Nekrose-Gift",
        gene_type=GeneType.MODIFIER,
        description="Infiziert getroffene Zellen mit anhaltendem nekrotischem Verfall.",
        biomass_cost=15.0,
        cast_delay_mod=0.06,
        damage=12.0,
        color=(130, 20, 40),
    ),
    Gene(
        id="MOD_NECROTIC_BURN",
        name="Nekrotischer Brand",
        gene_type=GeneType.MODIFIER,
        description="Entzündet Projektile mit nekrotischem Feuer, das Fleisch in Brand steckt.",
        biomass_cost=12.0,
        cast_delay_mod=0.02,
        damage=6.0,
        trail_material=MAT_FIRE,
        impact_material=MAT_FIRE,
        impact_material_count=4,
        color=(255, 140, 30),
    ),
    Gene(
        id="MOD_ACID_INFUSION",
        name="Säure-Imprägnierung",
        gene_type=GeneType.MODIFIER,
        description="Ummantelt Projektile mit kochender Magensäure für massive Gewebeätzung.",
        biomass_cost=18.0,
        cast_delay_mod=0.08,
        damage=15.0,
        trail_material=MAT_ACID,
        impact_material=MAT_ACID,
        impact_material_count=10,
        color=(80, 255, 40),
    ),
    Gene(
        id="MOD_CRITICAL_CELL_DEATH",
        name="Kritischer Zelltod",
        gene_type=GeneType.MODIFIER,
        description="Chance auf apokalyptischen Zelltod mit vierfachem Schadensmultiplikator.",
        biomass_cost=22.0,
        cast_delay_mod=0.05,
        critical_chance=0.25,
        damage=10.0,
        color=(255, 215, 0),
    ),
    Gene(
        id="MOD_RECOIL_DAMPING",
        name="Rückstoß-Dämpfung",
        gene_type=GeneType.MODIFIER,
        description="Hydraulische Knorpeldämpfer eliminieren Streuung und beschleunigen die Kadenz.",
        biomass_cost=6.0,
        cast_delay_mod=-0.06,
        spread_mod=-8.0,
        color=(140, 220, 210),
    ),
    Gene(
        id="MOD_PIERCING_SPINE",
        name="Durchdringende Chitinspitze",
        gene_type=GeneType.MODIFIER,
        description="Lässt Projektile durch weiches Fleisch hindurchschlagen.",
        biomass_cost=15.0,
        cast_delay_mod=0.10,
        piercing=True,
        damage=5.0,
        color=(140, 180, 220),
    ),
    Gene(
        id="MOD_PIERCING_HEAVY",
        name="Schweres Panzerbrechen",
        gene_type=GeneType.MODIFIER,
        description="Erhöht Durchschlagskapazität auf bis zu 6 getroffene Schichten.",
        biomass_cost=25.0,
        cast_delay_mod=0.18,
        piercing=True,
        damage=16.0,
        color=(100, 150, 240),
    ),
    Gene(
        id="MOD_MUTAGEN_COATING",
        name="Mutagen-Mantel",
        gene_type=GeneType.MODIFIER,
        description="Überzieht Projektile mit Mutagenschleim, der Gewebe in Tentakel verwandelt.",
        biomass_cost=25.0,
        cast_delay_mod=0.15,
        damage=10.0,
        trail_material=MAT_MUTAGEN,
        impact_material=MAT_MUTAGEN,
        impact_material_count=12,
        color=(230, 60, 255),
    ),
    Gene(
        id="MOD_SPEED_METABOLISM",
        name="Beschleunigter Stoffwechsel",
        gene_type=GeneType.MODIFIER,
        description="Erhöht Geschwindigkeit um 60% und reduziert Abklingzeit.",
        biomass_cost=6.0,
        cast_delay_mod=-0.06,
        recharge_mod=-0.08,
        speed=1.6,
        color=(80, 250, 210),
    ),
    Gene(
        id="MOD_SPEED_HYPER",
        name="Super-Katalysator",
        gene_type=GeneType.MODIFIER,
        description="Verdoppelt Projektilgeschwindigkeit (+120%) auf Überschallniveau.",
        biomass_cost=12.0,
        cast_delay_mod=-0.04,
        speed=2.2,
        color=(255, 240, 90),
    ),
    Gene(
        id="MOD_SPEED_DECEL",
        name="Schwebende Konservierung",
        gene_type=GeneType.MODIFIER,
        description="Bremst Projektile auf 35% ab, um stationäre Schutzbarrieren zu errichten.",
        biomass_cost=8.0,
        cast_delay_mod=0.02,
        speed=0.35,
        lifetime=60,
        color=(110, 160, 210),
    ),
    Gene(
        id="MOD_DAMAGE_BOOST",
        name="Zelluläre Hypertrophie",
        gene_type=GeneType.MODIFIER,
        description="Pumpt Nährstoffe in Projektile für solide +18 Basisschaden.",
        biomass_cost=16.0,
        cast_delay_mod=0.08,
        damage=18.0,
        color=(240, 100, 70),
    ),
    Gene(
        id="MOD_DAMAGE_MASSIVE",
        name="Riesenwuchs-Mutation",
        gene_type=GeneType.MODIFIER,
        description="Gewaltige Vergrößerung (+36 Schaden), erhöht jedoch die Ladezeit.",
        biomass_cost=32.0,
        cast_delay_mod=0.22,
        damage=36.0,
        radius=1.8,
        color=(255, 50, 50),
    ),
    Gene(
        id="MOD_BOUNCE_RUBBER",
        name="Knorpel-Elastizität",
        gene_type=GeneType.MODIFIER,
        description="Verleiht Projektilen die Fähigkeit, 3 Mal elastisch von Wänden abzuprallen.",
        biomass_cost=8.0,
        cast_delay_mod=0.02,
        bounce=3,
        color=(190, 235, 170),
    ),
    Gene(
        id="MOD_BOUNCE_SUPER",
        name="Hyper-Reflexion",
        gene_type=GeneType.MODIFIER,
        description="Prallt bis zu 6 Mal ab und gewinnt bei jedem Wandkontakt Schaden hinzu.",
        biomass_cost=16.0,
        cast_delay_mod=0.05,
        bounce=6,
        damage=8.0,
        color=(220, 255, 140),
    ),
    Gene(
        id="MOD_TRAIL_FIRE",
        name="Nekrotische Flammenspur",
        gene_type=GeneType.MODIFIER,
        description="Hinterlässt einen flammenden Schweif aus brennenden Aschepartikeln.",
        biomass_cost=10.0,
        cast_delay_mod=0.02,
        trail_material=MAT_FIRE,
        color=(255, 120, 10),
    ),
    Gene(
        id="MOD_TRAIL_ACID",
        name="Säure-Schleifspur",
        gene_type=GeneType.MODIFIER,
        description="Zieht eine kontinuierliche Lache ätzender Säure hinter dem Geschoss her.",
        biomass_cost=16.0,
        cast_delay_mod=0.06,
        trail_material=MAT_ACID,
        color=(100, 255, 60),
    ),
    Gene(
        id="MOD_TRAIL_BLOOD",
        name="Blutfährte",
        gene_type=GeneType.MODIFIER,
        description="Verströmt eine dichte Blutspur im Flug, die Wunden anzeigt.",
        biomass_cost=6.0,
        cast_delay_mod=0.01,
        trail_material=MAT_BLOOD,
        color=(180, 10, 20),
    ),
    Gene(
        id="MOD_TRAIL_MUTAGEN",
        name="Mutagen-Faden",
        gene_type=GeneType.MODIFIER,
        description="Glühender violetter Mutagenfaden zur dauerhaften Terrainveränderung.",
        biomass_cost=18.0,
        cast_delay_mod=0.08,
        trail_material=MAT_MUTAGEN,
        color=(210, 40, 255),
    ),
    Gene(
        id="MOD_TRAIL_SPORES",
        name="Sporen-Nebel",
        gene_type=GeneType.MODIFIER,
        description="Sprüht dichte Pilzsporen aus, die Feinde ersticken und blenden.",
        biomass_cost=10.0,
        cast_delay_mod=0.03,
        trail_material=MAT_SPORES,
        color=(175, 215, 60),
    ),
    Gene(
        id="MOD_EXPLOSION_BOOST",
        name="Tumor-Schwellung",
        gene_type=GeneType.MODIFIER,
        description="Vergrößert den Explosionsradius aller Projektile um +12 Einheiten.",
        biomass_cost=18.0,
        cast_delay_mod=0.10,
        explosion_radius=12,
        color=(245, 140, 40),
    ),
    Gene(
        id="MOD_EXPLOSION_MASSIVE",
        name="Super-Kavitation",
        gene_type=GeneType.MODIFIER,
        description="Erzeugt gigantische Druckwellen (+24 Explosionsradius) bei Detonation.",
        biomass_cost=34.0,
        cast_delay_mod=0.25,
        explosion_radius=24,
        color=(255, 70, 30),
    ),
    Gene(
        id="MOD_SPREAD_REDUCE",
        name="Neuro-Fokussierung",
        gene_type=GeneType.MODIFIER,
        description="Synaptische Feinjustierung verringert die Streuung um 12 Grad.",
        biomass_cost=4.0,
        cast_delay_mod=-0.02,
        spread_mod=-12.0,
        color=(120, 230, 240),
    ),
    Gene(
        id="MOD_SPREAD_CHAOS",
        name="Zell-Flackern",
        gene_type=GeneType.MODIFIER,
        description="Wildes chaotisches Streufeuer (+22 Grad Streuung), dafür +14 Schaden.",
        biomass_cost=8.0,
        cast_delay_mod=-0.05,
        spread_mod=22.0,
        damage=14.0,
        color=(255, 130, 180),
    ),
    Gene(
        id="MOD_LIFETIME_EXTEND",
        name="Telomer-Verlängerung",
        gene_type=GeneType.MODIFIER,
        description="Verhindert vorzeitigen Zelltod: +50 Ticks Lebensdauer für Reichweite.",
        biomass_cost=6.0,
        cast_delay_mod=0.02,
        lifetime=50,
        color=(160, 220, 150),
    ),
    Gene(
        id="MOD_LIFETIME_SHORTEN",
        name="Apoptose-Beschleuniger",
        gene_type=GeneType.MODIFIER,
        description="Kürzt Lebensdauer um 25 Ticks, bündelt die Energie jedoch für +12 Schaden.",
        biomass_cost=8.0,
        cast_delay_mod=-0.04,
        damage=12.0,
        lifetime=-25,
        color=(220, 90, 80),
    ),
    Gene(
        id="MOD_LIGHT_BIOLUM",
        name="Biolumineszenz-Glühen",
        gene_type=GeneType.MODIFIER,
        description="Projektile strahlen helles Licht aus, das dunkle Höhlenkammern erhellt.",
        biomass_cost=3.0,
        cast_delay_mod=-0.02,
        color=(255, 255, 160),
    ),
    Gene(
        id="MOD_VAMPIRIC_DRAIN",
        name="Hämo-Absorption",
        gene_type=GeneType.MODIFIER,
        description="Heilt den Symbioten bei Treffern gegen lebende Immunzellen um 1 HP.",
        biomass_cost=24.0,
        cast_delay_mod=0.12,
        vampiric=True,
        color=(210, 20, 60),
    ),
    Gene(
        id="MOD_POISON_CYTOX",
        name="Zytotoxische Lähmung",
        gene_type=GeneType.MODIFIER,
        description="Lässt Muskelgewebe getroffener Feinde erschlaffen und bremst sie aus.",
        biomass_cost=14.0,
        cast_delay_mod=0.06,
        slow_effect=True,
        damage=8.0,
        color=(170, 230, 40),
    ),
    Gene(
        id="MOD_ELECTRIC_CHARGE",
        name="Bio-Elektrische Ladung",
        gene_type=GeneType.MODIFIER,
        description="Lädt Projektile statisch auf; sendet Funken in nasse Flüssigkeiten.",
        biomass_cost=16.0,
        cast_delay_mod=0.05,
        damage=10.0,
        color=(60, 220, 255),
    ),
    Gene(
        id="MOD_FREEZE_CRYPTO",
        name="Kryo-Schock-Starre",
        gene_type=GeneType.MODIFIER,
        description="Entzieht Gewebe thermische Energie und lässt Feinde für Sekunden erstarren.",
        biomass_cost=20.0,
        cast_delay_mod=0.08,
        slow_effect=True,
        damage=12.0,
        color=(180, 240, 255),
    ),
    Gene(
        id="MOD_MASS_INCREASE",
        name="Knochen-Verdichtung",
        gene_type=GeneType.MODIFIER,
        description="Schwere molekulare Dichte wirft Physikkörper und Props gewaltig zurück.",
        biomass_cost=14.0,
        cast_delay_mod=0.10,
        damage=14.0,
        color=(215, 200, 180),
    ),
    Gene(
        id="MOD_GRAVITY_HEAVY",
        name="Schwere Schwerkraft",
        gene_type=GeneType.MODIFIER,
        description="Zieht Projektile parabolisch nach unten wie ein schweres Mörsergeschoss.",
        biomass_cost=8.0,
        cast_delay_mod=0.04,
        gravity=0.28,
        damage=15.0,
        color=(140, 120, 160),
    ),
    Gene(
        id="MOD_ANTI_GRAVITY",
        name="Antigravitations-Zelle",
        gene_type=GeneType.MODIFIER,
        description="Befreit Geschosse von Schwerkraft und lässt sie aufrecht in den Himmel steigen.",
        biomass_cost=8.0,
        cast_delay_mod=-0.02,
        gravity=-0.16,
        color=(170, 230, 240),
    ),

    # =========================================================================
    # 4. FORMATIONS & MULTICASTS (17 Cards)
    # =========================================================================
    Gene(
        id="MULTI_DOUBLE",
        name="Doppel-Injektion",
        gene_type=GeneType.MULTICAST,
        description="Feuert die nächsten 2 Gene gleichzeitig ab.",
        biomass_cost=4.0,
        multicast_count=2,
        spread_mod=4.0,
        color=(240, 180, 60),
    ),
    Gene(
        id="MULTI_TRIPLE",
        name="Dreifach-Kanal",
        gene_type=GeneType.MULTICAST,
        description="Feuert die nächsten 3 Gene im Fächer ab.",
        biomass_cost=8.0,
        multicast_count=3,
        spread_mod=8.0,
        color=(250, 140, 50),
    ),
    Gene(
        id="MULTI_QUAD",
        name="Vierfach-Pforte",
        gene_type=GeneType.MULTICAST,
        description="Entfesselt 4 Gene zeitgleich in einer breiten Schneise.",
        biomass_cost=12.0,
        multicast_count=4,
        spread_mod=12.0,
        color=(255, 110, 40),
    ),
    Gene(
        id="MULTI_PENTA",
        name="Fünffach-Cluster",
        gene_type=GeneType.MULTICAST,
        description="Feuert 5 Gene synchron in einer verheerenden Garbe ab.",
        biomass_cost=16.0,
        multicast_count=5,
        spread_mod=16.0,
        color=(255, 80, 50),
    ),
    Gene(
        id="MULTI_OCTA",
        name="Achtfach-Spreizung",
        gene_type=GeneType.MULTICAST,
        description="Monumentaler Ausstoß von 8 Genen gleichzeitig.",
        biomass_cost=25.0,
        multicast_count=8,
        spread_mod=24.0,
        color=(255, 40, 70),
    ),
    Gene(
        id="FORMATION_DOUBLE_HELIX",
        name="Doppel-Helix",
        gene_type=GeneType.MULTICAST,
        description="Entlässt 2 Projektile in umeinander kreisenden Sinus-Wellen.",
        biomass_cost=10.0,
        multicast_count=2,
        formation_type="DOUBLE_HELIX",
        color=(240, 120, 255),
    ),
    Gene(
        id="FORMATION_FAN_3",
        name="Fächer-Verzweigung 3",
        gene_type=GeneType.MULTICAST,
        description="Fächert 3 Projektile in exakten Winkeln (-15°, 0°, +15°) auf.",
        biomass_cost=8.0,
        multicast_count=3,
        formation_type="FAN_3",
        color=(245, 175, 50),
    ),
    Gene(
        id="FORMATION_FAN_5",
        name="Fächer-Verzweigung 5",
        gene_type=GeneType.MULTICAST,
        description="Fächert 5 Projektile über einen 60-Grad-Winkelbogen auf.",
        biomass_cost=14.0,
        multicast_count=5,
        formation_type="FAN_5",
        color=(255, 140, 40),
    ),
    Gene(
        id="FORMATION_RADIAL_8",
        name="Radial-Ausbruch 8",
        gene_type=GeneType.MULTICAST,
        description="Schleudert 8 Projektile in einem lückenlosen 360-Grad-Vollkreis heraus.",
        biomass_cost=22.0,
        multicast_count=8,
        formation_type="RADIAL_8",
        color=(255, 60, 100),
    ),
    Gene(
        id="FORMATION_RADIAL_12",
        name="Radial-Ausbruch 12",
        gene_type=GeneType.MULTICAST,
        description="Maximale Nova: 12 Projektile in alle Himmelsrichtungen verteilt.",
        biomass_cost=32.0,
        multicast_count=12,
        formation_type="RADIAL_12",
        color=(255, 20, 60),
    ),
    Gene(
        id="FORMATION_ORBITAL_2",
        name="Orbitale Bahnen 2",
        gene_type=GeneType.MULTICAST,
        description="Erzeugt 2 um den Symbioten kreisende Schutzgeschosse.",
        biomass_cost=14.0,
        multicast_count=2,
        formation_type="ORBITAL_2",
        color=(90, 210, 255),
    ),
    Gene(
        id="FORMATION_ORBITAL_4",
        name="Orbitale Bahnen 4",
        gene_type=GeneType.MULTICAST,
        description="Erzeugt 4 dichte kreisende Projektile als rotierende Bio-Mauer.",
        biomass_cost=24.0,
        multicast_count=4,
        formation_type="ORBITAL_4",
        color=(50, 180, 255),
    ),
    Gene(
        id="FORMATION_FRONT_BACK",
        name="Front- und Heck-Schuss",
        gene_type=GeneType.MULTICAST,
        description="Schießt gleichzeitig nach vorne (0°) und nach hinten (180°).",
        biomass_cost=6.0,
        multicast_count=2,
        formation_type="FRONT_BACK",
        color=(180, 240, 120),
    ),
    Gene(
        id="FORMATION_TRI_DIRECTIONAL",
        name="Drei-Wege-Kreuz",
        gene_type=GeneType.MULTICAST,
        description="Schießt in 3 symmetrischen Richtungen (0°, 120°, 240°).",
        biomass_cost=10.0,
        multicast_count=3,
        formation_type="TRI_DIRECTIONAL",
        color=(210, 240, 80),
    ),
    Gene(
        id="FORMATION_QUAD_CARDINAL",
        name="Vier-Himmelsrichtungen",
        gene_type=GeneType.MULTICAST,
        description="Schießt kreuzförmig in alle 4 Richtungen (0°, 90°, 180°, 270°).",
        biomass_cost=14.0,
        multicast_count=4,
        formation_type="QUAD_CARDINAL",
        color=(240, 200, 50),
    ),
    Gene(
        id="FORMATION_HEX_BURST",
        name="Hexagon-Ausstoß",
        gene_type=GeneType.MULTICAST,
        description="Feuert 6 Geschosse in perfekter hexagonaler Sternformation ab.",
        biomass_cost=18.0,
        multicast_count=6,
        formation_type="HEX_BURST",
        color=(255, 150, 60),
    ),
    Gene(
        id="FORMATION_LINE_STREAM",
        name="Lineare Salve",
        gene_type=GeneType.MULTICAST,
        description="Entlässt 3 Geschosse gestaffelt in exakt gleicher Schusslinie.",
        biomass_cost=10.0,
        multicast_count=3,
        formation_type="LINE_STREAM",
        color=(255, 220, 110),
    ),

    # =========================================================================
    # 5. META-GENES & REPLICATION CATALYSTS (8 Cards)
    # =========================================================================
    Gene(
        id="POLYMERASE_X2",
        name="Polymerase-Duplikator x2",
        gene_type=GeneType.META,
        description="Verdoppelt den nachfolgenden Gen-Effekt im Deck mit Rekursions-Bremse.",
        biomass_cost=15.0,
        cast_delay_mod=0.08,
        meta_type="DIVIDE_2",
        meta_multiplier=2,
        color=(255, 215, 60),
    ),
    Gene(
        id="POLYMERASE_X3",
        name="Polymerase-Duplikator x3",
        gene_type=GeneType.META,
        description="Verdreifacht den nachfolgenden Gen-Effekt mit Rekursions-Dämpfung.",
        biomass_cost=25.0,
        cast_delay_mod=0.15,
        meta_type="DIVIDE_3",
        meta_multiplier=3,
        color=(255, 190, 40),
    ),
    Gene(
        id="POLYMERASE_X4",
        name="Polymerase-Duplikator x4",
        gene_type=GeneType.META,
        description="Vervierfacht den nachfolgenden Gen-Effekt für gigantische Kaskaden.",
        biomass_cost=38.0,
        cast_delay_mod=0.22,
        meta_type="DIVIDE_4",
        meta_multiplier=4,
        color=(255, 150, 30),
    ),
    Gene(
        id="POLYMERASE_X10",
        name="Polymerase-Duplikator x10",
        gene_type=GeneType.META,
        description="Zehnfacht das nachfolgende Gen. Verbraucht massive Biomasse, streng rekursionsgebremst.",
        biomass_cost=70.0,
        cast_delay_mod=0.45,
        meta_type="DIVIDE_10",
        meta_multiplier=10,
        color=(255, 70, 10),
    ),
    Gene(
        id="CIRCULAR_RNA_LOOP",
        name="Zirkuläre RNA-Schleife",
        gene_type=GeneType.META,
        description="Ruft das erste Gen der Kanüle erneut auf und schließt die Sequenz zyklisch ab.",
        biomass_cost=12.0,
        cast_delay_mod=0.06,
        meta_type="LOOP_FIRST",
        color=(140, 240, 210),
    ),
    Gene(
        id="RIBOSOME_CATALYST",
        name="Ribosomen-Katalysator",
        gene_type=GeneType.META,
        description="Feuert ein zufälliges Gen aus der Kanüle ohne Biomasse-Verbrauch (zieht bei Mangel HP ab).",
        biomass_cost=0.0,
        cast_delay_mod=0.04,
        meta_type="RANDOM_DISCARD",
        color=(220, 140, 255),
    ),
    Gene(
        id="UR_CODE_ALPHA",
        name="Ur-Code Alpha",
        gene_type=GeneType.META,
        description="Repliziert das exakt erste Gen der Kanüle ohne zusätzliche Biomassekosten.",
        biomass_cost=5.0,
        cast_delay_mod=0.02,
        meta_type="COPY_FIRST",
        color=(80, 220, 255),
    ),
    Gene(
        id="UR_CODE_OMEGA",
        name="Ur-Code Omega",
        gene_type=GeneType.META,
        description="Repliziert das letzte Gen der Kanüle ohne zusätzliche Biomassekosten.",
        biomass_cost=5.0,
        cast_delay_mod=0.02,
        meta_type="COPY_LAST",
        color=(240, 80, 255),
    ),
]

GENE_DICT = {gene.id: gene for gene in GENE_LIBRARY}

